# Generated by Django 3.2.22 on 2023-11-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_predefined_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tagline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Tagline'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tagline'),
        ),
    ]
